import json
with open("config.json") as config_file:
    CONFIG = json.load(config_file)

PROJECT_NAME = CONFIG["PROJECT_NAME"]
CHIPS_BIN = CONFIG["CHIPS_BIN"]
CHIPS_JSON = CONFIG["CHIPS_JSON"]
BROWSER_EXPORT_FILE = CONFIG["BROWSER_EXPORT_FILE"]
MEDIUM_DIR = CONFIG["MEDIUM_DIR"]
DATASET_URL = CONFIG["DATASET_URL"]
USERCODE = CONFIG["USERCODE"]
